# -*- coding: utf-8 -*-
"""appy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcVsIs7MA2P1djB0Yahg7Ls4j6EFoyLm

### Training and Saving the MNIST Model

Since the model file `modelo_mnist.keras` was not found, we will train a simple Convolutional Neural Network (CNN) on the MNIST dataset and save it. This model will then be used by the Streamlit application for digit recognition.
"""

import tensorflow as tf
import numpy as np

# 1. Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

# 2. Preprocess the data
x_train = x_train.reshape(-1, 28, 28, 1).astype('float32') / 255.0
x_test = x_test.reshape(-1, 28, 28, 1).astype('float32') / 255.0

y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

print("MNIST dataset loaded and preprocessed.")
print(f"x_train shape: {x_train.shape}")
print(f"y_train shape: {y_train.shape}")

"""### Building the CNN Model

We'll define a simple CNN architecture suitable for MNIST digit classification.
"""

# 3. Build the CNN model
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.summary()

print("Model architecture defined.")

"""### Compiling and Training the Model

The model will be compiled with the Adam optimizer and categorical crossentropy loss, then trained for a few epochs.
"""

# 4. Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

print("Model compiled.")

# 5. Train the model
history = model.fit(x_train, y_train, epochs=5, batch_size=64, validation_split=0.2)

print("Model training complete.")

"""### Evaluating and Saving the Model

After training, we will evaluate the model's performance on the test set and then save it in the `.keras` format.
"""

# Evaluate the model
loss, accuracy = model.evaluate(x_test, y_test, verbose=0)
print(f"Test Accuracy: {accuracy:.4f}")

# 6. Save the trained model
model.save('modelo_mnist.keras')
print("Model saved as 'modelo_mnist.keras'.")

import sys
!{sys.executable} -m pip install streamlit tensorflow streamlit-drawable-canvas opencv-python numpy
import streamlit as st
import tensorflow as tf
from streamlit_drawable_canvas import st_canvas
import cv2
import numpy as np

# Configuración de la página
st.set_page_config(page_title="IA Digit Recognizer")
st.title("Reconocedor de Dígitos en Tiempo Real")
st.write("Dibuja un número del 0 al 9 en el recuadro negro.")

# 1. Cargar el modelo guardado
@st.cache_resource
def load_my_model():
    return tf.keras.models.load_model('modelo_mnist.keras')

model = load_my_model()

# 2. Crear el lienzo (Canvas) para dibujar
canvas_result = st_canvas(
    fill_color="white",
    stroke_width=20,
    stroke_color="white",
    background_color="black",
    height=280,
    width=280,
    drawing_mode="freedraw",
    key="canvas"
)

# 3. Procesar el dibujo y predecir
if canvas_result.image_data is not None:
    # Convertir el dibujo a 28x28 píxeles (formato MNIST)
    img = cv2.resize(canvas_result.image_data.astype('uint8'), (28, 28))

    # Convertir a escala de grises (RGBA a GRAY)
    img = cv2.cvtColor(img, cv2.COLOR_RGBA2GRAY)

    # Invertir colores (el canvas tiene fondo negro, MNIST espera fondo negro)
    # pero necesitamos que el número sea blanco
    _, img = cv2.threshold(img, 128, 255, cv2.THRESH_BINARY)

    img = img / 255.0  # Normalizar

    # Asegurar que tenga la forma correcta (28, 28, 1)
    img = np.expand_dims(img, axis=-1)

    # Predicción
    pred = model.predict(img.reshape(1, 28, 28, 1))
    clase = np.argmax(pred)
    confianza = np.max(pred)

    # 4. Mostrar resultados con Umbral de Seguridad
    st.subheader(f"Resultado: {clase}")

    if confianza < 0.80:
        st.warning(f"Confianza baja ({confianza:.2%}). ¿Podrías dibujar más claro?")
    else:
        st.success(f"Confianza alta: {confianza:.2%}")

    st.bar_chart(pred[0])  # Visualización de probabilidades